apiVersion: v1
kind: Service
metadata:
  name: uaa
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "uaa-k8srelease.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "uaa-k8srelease.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
