apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-tomcat-config
  namespace: {{ .Release.Namespace }}
data:
  server.xml: |
    <?xml version='1.0' encoding='utf-8'?>
    <Server port="-1">
      <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
      <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
      <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
      <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
      <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
      <!-- <Listener className="org.cloudfoundry.identity.uaa.web.tomcat.UaaStartupFailureListener" /> -->

      <Service name="Catalina">
        <!-- bindOnInit & maxHttpHeaderSize -->
        <Connector class="org.apache.coyote.http11.Http11NioProtocol"
                   protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   address="0.0.0.0"
                   port="8080"
                   bindOnInit="true"
                   maxHttpHeaderSize="14336"
        />

        <Connector class="org.apache.coyote.http11.Http11NioProtocol" protocol="HTTP/1.1" connectionTimeout="20000"
                   scheme="https"
                   port="8443"
                   SSLEnabled="true"
                   sslEnabledProtocols="TLSv1.2"
                   ciphers="TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
                   secure="true"
                   clientAuth="false"
                   sslProtocol="TLS"
                   keystoreFile="/var/run/secrets/keystore.pkcs12"
                   keystoreType="PKCS12"
                   keyAlias="uaa_ssl_cert"
                   keystorePass="k0*l*s3cur1tyr0ck$"
                   bindOnInit="false"
                   maxHttpHeaderSize="14336"
        />

        <!-- Valves are placed differently, configured differently.-->
        <!-- autoDeploy -->
        <Engine name="Catalina" defaultHost="localhost">
          <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="false" failCtxIfServletStartFails="true">
            <Valve className="org.apache.catalina.valves.RemoteIpValve"
                   remoteIpHeader="x-forwarded-for"
                   protocolHeader="x-forwarded-proto"
                   internalProxies="10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}"
            />
            <Valve className="org.apache.catalina.valves.AccessLogValve"
                   directory="/workspace/logs/"
                   prefix="localhost_access"
                   suffix=".log"
                   rotatable="false"
                   pattern="%h %l %u %t &quot;%r&quot; %s %b"/>
            <Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false"/>
            <Listener className='org.cloudfoundry.tomcat.lifecycle.ApplicationStartupFailureDetectingLifecycleListener'/>
          </Host>
        </Engine>
      </Service>
    </Server>

